-- Comments in SQL Start with dash-dash --
--1.SELECT * FROM analytics WHERE id = 1880;
--2. SELECT id, app_name FROM analytics WHERE last_updated = '2018-08-01';
--3. SELECT category, COUNT(id) FROM analytics GROUP BY (category);
--4. SELECT app_name, reviews FROM analytics ORDER BY reviews DESC LIMIT 5;
--5. SELECT app_name, reviews FROM analytics WHERE rating >= 4.8 ORDER BY reviews DESC LIMIT 1;
--6. SELECT category, AVG(rating) FROM analytics GROUP BY category,rating  ORDER BY rating DESC;
--7. SELECT app_name, rating, price FROM analytics WHERE rating < 3 ORDER BY price DESC LIMIT 1;
--8. SELECT app_name, rating FROM analytics WHERE min_installs < 50 AND rating IS NOT NULL ORDER BY rating DESC;
--9.SELECT app_name FROM analytics WHERE rating < 3 AND reviews >= 10000;
--10. SELECT app_name FROM analytics WHERE price > 0.10 AND price < 1.00 ORDER BY price DESC LIMIT 10;
--11. SELECT app_name FROM analytics ORDER BY last_updated ASC LIMIT 1;
--12.SELECT app_name FROM analytics WHERE price = (SELECT MAX(price) FROM analytics);
--13. SELECT COUNT(reviews) FROM analytics;
--14.SELECT category FROM analytics GROUP BY category HAVING count(*) > 300;
--15. SELECT app_name, reviews, min_installs, 
--        CAST(min_installs AS FLOAT)/reviews AS proportion 
-- FROM analytics 
-- WHERE min_installs >= 100000 AND reviews > 0 
-- ORDER BY proportion DESC 
-- LIMIT 1;


--FS1. 